---
kind: pipeline
type: docker
name: vortex

steps:
  - name: Build & Test
    image: golang:1.16.6
    commands:
      - go build
      - go test -timeout 30s ./... -race

trigger:
  branch:
    - master
---
kind: signature
hmac: 02ce0af0ae8905b42809318887210944fea9b7f7a22a15057ba676927ded1b73
...
